//! Static project metadata, resume content, about specifications, and retro architecture diagrams.

#[derive(Debug, Clone)]
pub struct Project {
    pub title: &'static str,
    pub slug: &'static str,
    pub tldr: &'static str,
    pub tags: &'static [&'static str],
    pub wip: bool,
}

pub static PROJECTS: &[Project] = &[
    Project {
        title: "RAPS",
        slug: "raps",
        tldr: "An open-core Rust CLI and MCP server that exposes 16 Autodesk Platform Services APIs to AI agents via typed contracts and 51 robust tools.",
        tags: &["rust", "mcp", "agents", "cad", "python"],
        wip: false,
    },
    Project {
        title: "Dry",
        slug: "dry",
        tldr: "A typed, units-aware multi-level IR and Rust engine for algorithmic machine toolpaths (FFF/CNC/laser/robot) — LLVM/MLIR for machine motion.",
        tags: &["rust", "compilers", "cnc", "3d-printing"],
        wip: false,
    },
    Project {
        title: "Glueball",
        slug: "glueball",
        tldr: "A CAD-agnostic routed-assembly solver for frames, weldments, tube & pipe, and wire harnesses that compiles 3D graphs into deterministic build plans without linking a geometry kernel.",
        tags: &["rust", "cad-engine", "solvers", "compilers"],
        wip: false,
    },
    Project {
        title: "Klen",
        slug: "klen",
        tldr: "A universal kernel for describing, executing, and formally verifying system safety contracts and state machine invariants in Lean 4.",
        tags: &["lean-4", "formal-methods", "verification", "rust"],
        wip: false,
    },
    Project {
        title: "FTTH CAD Lineage",
        slug: "ftth-cad-lineage",
        tldr: "Four generations of FTTH design tooling (FiberCAD -> Gluon -> Photon -> Muon). Gluon replaces an LLM-authors-the-drawing approach with a deterministic pipeline.",
        tags: &["python", "autocad", "agents", "llm"],
        wip: false,
    },
    Project {
        title: "VPA",
        slug: "vpa",
        tldr: "Verifiable Physical Agent: A domain-specific language, optimizing compiler, and formally verified VM for hard real-time physical automation.",
        tags: &["compilers", "formal-verification", "assembly"],
        wip: false,
    },
    Project {
        title: "Barvinca",
        slug: "barvinca",
        tldr: "A headless, high-throughput digital asset management and vector transformation engine deployed on Cloudflare Workers.",
        tags: &["typescript", "cloudflare-workers", "turborepo"],
        wip: false,
    },
    Project {
        title: "Upyr",
        slug: "upyr",
        tldr: "An offline-first, local privacy-preserving PII redaction and named-entity sanitization tool in pure Rust for LLM context ingestion pipelines.",
        tags: &["rust", "nlp", "privacy"],
        wip: false,
    },
    Project {
        title: "Dryer",
        slug: "dryer",
        tldr: "Embedded firmware and deterministic control loop for custom active filament drying chamber with closed-loop PID humidity regulation.",
        tags: &["rust", "embedded", "3d-printing"],
        wip: false,
    },
    Project {
        title: "Verbacorpus",
        slug: "verbacorpus",
        tldr: "A structured lexicon and etymological database API of Ukrainian language with linguistic graph search.",
        tags: &["typescript", "pwa", "api"],
        wip: false,
    },
    Project {
        title: "Ukrainian Pattern Archive",
        slug: "ukrainian-pattern-archive",
        tldr: "A structured, deduplicated corpus of Ukrainian vyshyvanka folk-embroidery charts powered by an OCR and computational geometry pipeline.",
        tags: &["python", "ocr", "computational-geometry"],
        wip: false,
    },
    Project {
        title: "Nasinnia",
        slug: "nasinnia",
        tldr: "A raster-first API and rendering engine for historical Ukrainian typography, pixel fonts, and bitmap glyph matrix generation.",
        tags: &["typescript", "typography", "canvas"],
        wip: false,
    },
    Project {
        title: "Criticality Lab",
        slug: "criticality-lab",
        tldr: "Interactive GPU-accelerated simulation of self-organized criticality, sandpile models, and percolation thresholds using WebGPU.",
        tags: &["rust", "wgpu", "simulation"],
        wip: false,
    },
    Project {
        title: "Tawara",
        slug: "tawara",
        tldr: "A WebAssembly runtime verification harness and memory assertion tool for sandboxed untrusted plugin evaluation.",
        tags: &["rust", "wasm", "verification"],
        wip: false,
    },
    Project {
        title: "Media Glitch",
        slug: "media-glitch",
        tldr: "Deterministic databending and bitstream corruptor implemented in WebAssembly for algorithmic visual glitch generation.",
        tags: &["rust", "wasm", "glitch-art"],
        wip: false,
    },
    Project {
        title: "Emoji Madness",
        slug: "emoji-madness",
        tldr: "Metal-accelerated cellular automata and particle system generating generative dynamic wallpaper simulations.",
        tags: &["swift", "metal", "generative-art"],
        wip: false,
    },
];

pub const RESUME_MAX_SCROLL: usize = 80;
pub const ABOUT_MAX_SCROLL: usize = 52;

pub static RESUME_LINES_80: &[(&str, u8, bool)] = &[
    ("CAREER EXPERIENCE & TECHNICAL IMPACT SUMMARY:", 6, true),
    ("┌────────────┬───────────────────────┬──────────┬────────────────────────┐", 7, false),
    ("│ Period     │ Role & Organization   │ Domain   │ Deliverables & Impact  │", 6, true),
    ("├────────────┼───────────────────────┼──────────┼────────────────────────┤", 7, false),
    ("│ 2026-Pres. │ Indep. Consultant/Dev │ CAD / AI │ RAPS: 51 MCP tools,    │", 5, false),
    ("│            │ Self-Employed, Remote │ Rust/APS │ 300x project provision │", 4, false),
    ("├────────────┼───────────────────────┼──────────┼────────────────────────┤", 7, false),
    ("│ 2021-2026  │ Senior Developer      │ Sitecore │ Azure OpenAI RAG (5 tm)│", 5, false),
    ("│            │ Remote, Ukraine       │ .NET/AI  │ Microservices, CI/CD   │", 4, false),
    ("├────────────┼───────────────────────┼──────────┼────────────────────────┤", 7, false),
    ("│ 2020-2021  │ Senior Developer      │ Sitecore │ Cloud platform data ly │", 5, false),
    ("│            │ Kuala Lumpur, Malaysia│ Cloud/DB │ Mentoring & tech hires │", 4, false),
    ("├────────────┼───────────────────────┼──────────┼────────────────────────┤", 7, false),
    ("│ 2019-2020  │ Cloud Operations Eng. │ Sitecore │ Multi-region Azure SLO,│", 5, false),
    ("│            │ Dnipro, Ukraine       │ AzureOps │ Incident response,toil │", 4, false),
    ("├────────────┼───────────────────────┼──────────┼────────────────────────┤", 7, false),
    ("│ 2015-2019  │ Software Dev / ETL    │ Ciklum & │ Enterprise ETL, SSIS,  │", 5, false),
    ("│            │ CAD/PDM Consultant    │ AMCBridge│ CAD/PDM R&D, ADN writer│", 4, false),
    ("├────────────┼───────────────────────┼──────────┼────────────────────────┤", 7, false),
    ("│ 2012-2015  │ PDM / PLM Manager     │ Hydrotech│ CAD/PLM office platform│", 5, false),
    ("│            │ Dnipro, Ukraine       │ CAD/PLM  │ First Forge/APS in '14 │", 4, false),
    ("└────────────┴───────────────────────┴──────────┴────────────────────────┘", 7, false),
    ("", 5, false),
    ("PRODUCTION AI & RAG TRACK RECORD (Sitecore, 2023 - 2026):", 8, true),
    ("• Built Azure OpenAI (GPT) RAG system over internal docs & CI/CD logs.", 5, false),
    ("• Used daily across 5 engineering teams to triage CI/CD build failures.", 5, false),
    ("• HIPAA-compliant, zero data leakage with automated verification checks.", 5, false),
    ("• Microservices backend across multi-region Azure production deployments.", 5, false),
    ("", 5, false),
    ("AGENTIC PLATFORMS, CAD/PLM & OPEN-SOURCE (2025 - 2026):", 11, true),
    ("• Author of RAPS: Rust platform & MCP server for 16 Autodesk APS APIs.", 5, false),
    ("• Exposes 230+ commands & 51 MCP tools; 300x provisioning acceleration.", 5, false),
    ("• Cloudflare Workers/Containers MCP gateway with per-license isolation.", 5, false),
    ("• Developer of Dry (motion compiler IR) & Photon (deterministic planner).", 5, false),
    ("", 5, false),
    ("CORE COMPETENCIES & TECHNICAL EXPERTISE:", 9, true),
    ("┌───────────────────────────────────┬────────────────────────────────────┐", 7, false),
    ("│ LANGUAGES & PLATFORMS             │ AI, CLOUD & DOMAIN INFRASTRUCTURE  │", 6, true),
    ("├───────────────────────────────────┼────────────────────────────────────┤", 7, false),
    ("│ ■ C# / .NET (12y) - Core Backend  │ ■ AI: Model Context Protocol (MCP) │", 5, false),
    ("│ ■ Rust (3y) - Systems & Tooling   │ ■ LLM: Azure OpenAI RAG, Prompts   │", 5, false),
    ("│ ■ TypeScript / Node.js (8y)       │ ■ Cloud: Cloudflare (Workers, D1)  │", 5, false),
    ("│ ■ Python (6y) - Async / FastAPI   │ ■ Cloud: Azure (Multi-region, AVD) │", 5, false),
    ("│ ■ SQL, SSIS & T-SQL Optimization  │ ■ CAD/PLM: Autodesk APS, Vault, BIM│", 5, false),
    ("└───────────────────────────────────┴────────────────────────────────────┘", 7, false),
    ("", 5, false),
    ("HONORS, RECOGNITION & AWARDS:", 14, true),
    ("• Autodesk Expert Elite -- current member (top ~100 individuals globally).", 5, false),
    ("• Autodesk Developer Network (ADN) member since 2012, writer since 2013.", 5, false),
    ("• Author, Autodesk Vault Programmer's Cookbook & App Store CAD tools.", 5, false),
    ("• RAPS recognized by Autodesk Developer Advocacy; invited to demo (2026).", 5, false),
    ("", 5, false),
    ("EDUCATION & CREDENTIALS:", 12, true),
    ("• Master's Degree, Computer Science (Computer Engineer, 2003 - 2008).", 5, false),
    ("  Oles Honchar Dnipro National University (Dnipro, Ukraine).", 5, false),
    ("• Continuous R&D: Agentic harnesses, zero-alloc Rust, deterministic eval.", 4, false),
    ("", 5, false),
    ("AVAILABILITY & LOCATION:", 6, true),
    ("• Target: Senior / Staff / Lead / Architect (Systems, AI Infra, CAD/PLM).", 5, false),
    ("• Location: Vinnytsia, Ukraine / Remote worldwide (no relocation).", 5, false),
    ("• Direct contact: dyemelianov@icloud.com | GitHub: @dmytro-yemelianov", 7, true),
];

pub static RESUME_LINES_40: &[(&str, u8, bool)] = &[
    ("CAREER EXPERIENCE & TECHNICAL IMPACT:", 6, true),
    ("┌────────────────────────────────────┐", 7, false),
    ("│ 2026-Pres: Indep. Consultant / Dev │", 6, true),
    ("│ Self-Employed | Vinnytsia · Remote │", 5, false),
    ("│ • RAPS: 51 MCP tools for Autodesk  │", 5, false),
    ("│ • 300x project provision speedup   │", 5, false),
    ("├────────────────────────────────────┤", 7, false),
    ("│ 2021-2026: Senior Developer        │", 6, true),
    ("│ Sitecore | .NET Backend & AI Infra │", 5, false),
    ("│ • Azure OpenAI RAG across 5 teams  │", 5, false),
    ("│ • Multi-region production services │", 5, false),
    ("├────────────────────────────────────┤", 7, false),
    ("│ 2020-2021: Senior Developer        │", 6, true),
    ("│ Sitecore | Kuala Lumpur, Malaysia  │", 5, false),
    ("│ • Cloud platform data layer design │", 5, false),
    ("│ • Mentored engineers & hiring      │", 5, false),
    ("├────────────────────────────────────┤", 7, false),
    ("│ 2019-2020: Cloud Operations Eng.   │", 6, true),
    ("│ Sitecore | Azure Managed Cloud SLO │", 5, false),
    ("│ • Incident response, toil automate │", 5, false),
    ("├────────────────────────────────────┤", 7, false),
    ("│ 2015-2019: Software Dev / ETL      │", 6, true),
    ("│ Ciklum & AMC Bridge | CAD/PDM R&D  │", 5, false),
    ("│ • Enterprise ETL, SQL Server, SSIS │", 5, false),
    ("│ • ADN technical writer since 2013  │", 5, false),
    ("├────────────────────────────────────┤", 7, false),
    ("│ 2012-2015: PDM / PLM Manager       │", 6, true),
    ("│ Hydrotech Engineering | CAD/PLM    │", 5, false),
    ("│ • First Autodesk Forge apps ('14)  │", 5, false),
    ("└────────────────────────────────────┘", 7, false),
    ("", 5, false),
    ("PRODUCTION AI & RAG (Sitecore 23-26):", 8, true),
    ("• Built Azure OpenAI (GPT) RAG system", 5, false),
    ("  over internal docs & CI/CD logs.", 5, false),
    ("• Used daily across 5 global teams  ", 5, false),
    ("  to triage build failures rapidly. ", 5, false),
    ("• HIPAA-compliant, zero data leakage ", 5, false),
    ("  with automated verification checks.", 5, false),
    ("", 5, false),
    ("AGENTIC PLATFORMS & CAD/PLM (25-26): ", 11, true),
    ("• Author of RAPS: Rust platform with", 5, false),
    ("  51 Model Context Protocol tools.  ", 5, false),
    ("• 16 Autodesk APIs, 230+ CLI cmds,  ", 5, false),
    ("  300x provisioning acceleration.   ", 5, false),
    ("• Cloudflare Workers/Containers host ", 5, false),
    ("  with per-license isolation & auth. ", 5, false),
    ("• Developer of Dry & Photon services.", 5, false),
    ("", 5, false),
    ("CORE COMPETENCIES & EXPERTISE:       ", 9, true),
    ("┌────────────────────────────────────┐", 3, false),
    ("│ LANGUAGES & PLATFORMS              │", 6, true),
    ("├────────────────────────────────────┤", 3, false),
    ("│ • C# / .NET (12y), Rust (3y)       │", 5, false),
    ("│ • TypeScript / Node.js (8y)        │", 5, false),
    ("│ • Python (6y, FastAPI, Asyncio)   │", 5, false),
    ("│ • SQL Server, SSIS, T-SQL, D1      │", 5, false),
    ("├────────────────────────────────────┤", 3, false),
    ("│ AI, CLOUD & DOMAIN INFRASTRUCTURE  │", 6, true),
    ("├────────────────────────────────────┤", 3, false),
    ("│ • Model Context Protocol (MCP)     │", 5, false),
    ("│ • Azure OpenAI, RAG, Prompt Evals  │", 5, false),
    ("│ • Cloudflare Workers, Containers   │", 5, false),
    ("│ • Azure (Multi-region, AVD), IaC   │", 5, false),
    ("│ • Autodesk APS, Vault, BIM, Forma  │", 5, false),
    ("└────────────────────────────────────┘", 3, false),
    ("", 5, false),
    ("HONORS, RECOGNITION & AWARDS:        ", 14, true),
    ("• Autodesk Expert Elite (current,    ", 5, false),
    ("  ~100 recognized globally).        ", 5, false),
    ("• Autodesk Developer Network (ADN)   ", 5, false),
    ("  member since 2012, writer 2013.   ", 5, false),
    ("• Author, Autodesk Vault Cookbook    ", 5, false),
    ("  and Autodesk App Store add-ins.   ", 5, false),
    ("• RAPS maintainer (Autodesk demo 26).", 5, false),
    ("", 5, false),
    ("EDUCATION & CREDENTIALS:             ", 12, true),
    ("• Master's Degree in Computer Science", 5, false),
    ("  (Computer Engineer, 2003-2008).   ", 5, false),
    ("  Oles Honchar Dnipro National Univ.", 5, false),
    ("", 5, false),
    ("AVAILABILITY & LOCATION:             ", 6, true),
    ("• Target: Senior / Staff / Lead /    ", 5, false),
    ("  Architect (Systems, AI, CAD/PLM). ", 5, false),
    ("• Location: Vinnytsia, Ukraine /     ", 5, false),
    ("  Remote worldwide (no relocation). ", 5, false),
    ("• Contact: dyemelianov@icloud.com    ", 7, true),
    ("• GitHub: @dmytro-yemelianov        ", 7, true),
    ("• Web: https://yemelianov.dev        ", 7, true),
];

pub static RESUME_LINES_32: &[(&str, u8, bool)] = &[
    ("CAREER & IMPACT SUMMARY:", 6, true),
    ("┌───────────────────────────┐", 7, false),
    ("│ 2026-Pres | Self-Employed │", 6, true),
    ("│ Indep. Consultant & Dev   │", 5, false),
    ("│ • RAPS: 51 MCP tools      │", 5, false),
    ("│ • 300x project provision  │", 5, false),
    ("├───────────────────────────┤", 7, false),
    ("│ 2021-2026 | Sitecore      │", 6, true),
    ("│ Senior Developer (.NET)   │", 5, false),
    ("│ • Azure OpenAI RAG (5 tm) │", 5, false),
    ("│ • Multi-region production │", 5, false),
    ("├───────────────────────────┤", 7, false),
    ("│ 2020-2021 | Sitecore KL   │", 6, true),
    ("│ Senior Developer          │", 5, false),
    ("│ • Cloud platform data     │", 5, false),
    ("│ • Engineering mentorship  │", 5, false),
    ("├───────────────────────────┤", 7, false),
    ("│ 2019-2020 | Sitecore      │", 6, true),
    ("│ Cloud Operations Engineer │", 5, false),
    ("│ • Azure Managed Cloud SLO │", 5, false),
    ("│ • Incident response, toil │", 5, false),
    ("├───────────────────────────┤", 7, false),
    ("│ 2015-2019 | Ciklum & AMC  │", 6, true),
    ("│ Software Dev / ETL / PDM  │", 5, false),
    ("│ • Enterprise ETL, SSIS    │", 5, false),
    ("│ • CAD/PDM R&D, ADN writer │", 5, false),
    ("├───────────────────────────┤", 7, false),
    ("│ 2012-2015 | Hydrotech     │", 6, true),
    ("│ PDM / PLM Manager         │", 5, false),
    ("│ • First Forge/APS apps    │", 5, false),
    ("└───────────────────────────┘", 7, false),
    ("", 5, false),
    ("PRODUCTION AI (Sitecore):  ", 8, true),
    ("• Built Azure OpenAI RAG    ", 5, false),
    ("  system on logs & docs.    ", 5, false),
    ("• 5 teams daily, triaging   ", 5, false),
    ("  CI/CD build failures.     ", 5, false),
    ("• HIPAA-compliant, zero     ", 5, false),
    ("  data leakage guaranteed.  ", 5, false),
    ("", 5, false),
    ("AGENTIC & CAD/PLM (25-26):  ", 11, true),
    ("• RAPS: 51 MCP tools        ", 5, false),
    ("  for 16 Autodesk APIs.     ", 5, false),
    ("• 230+ CLI cmds, 300x speed ", 5, false),
    ("  in project provisioning.  ", 5, false),
    ("• Cloudflare Workers/KV     ", 5, false),
    ("  hosted MCP gateway.       ", 5, false),
    ("• Dry & Photon services.    ", 5, false),
    ("", 5, false),
    ("CORE COMPETENCIES:          ", 9, true),
    ("┌───────────────────────────┐", 3, false),
    ("│ LANGUAGES & PLATFORMS     │", 6, true),
    ("├───────────────────────────┤", 3, false),
    ("│ • C# / .NET (12y)         │", 5, false),
    ("│ • TypeScript / Node (8y)  │", 5, false),
    ("│ • Python (FastAPI, 6y)    │", 5, false),
    ("│ • Rust (3y production)    │", 5, false),
    ("│ • SQL Server, SSIS, T-SQL │", 5, false),
    ("├───────────────────────────┤", 3, false),
    ("│ AI, CLOUD & DOMAIN        │", 6, true),
    ("├───────────────────────────┤", 3, false),
    ("│ • MCP Servers & Claude    │", 5, false),
    ("│ • Azure OpenAI, RAG, Eval │", 5, false),
    ("│ • Cloudflare Workers, D1  │", 5, false),
    ("│ • Azure Multi-region, AVD │", 5, false),
    ("│ • Autodesk APS, Vault, BIM│", 5, false),
    ("└───────────────────────────┘", 3, false),
    ("", 5, false),
    ("HONORS & AWARDS:            ", 14, true),
    ("• Autodesk Expert Elite     ", 5, false),
    ("  (top ~100 globally).      ", 5, false),
    ("• Autodesk Developer Net    ", 5, false),
    ("  member '12, writer '13.   ", 5, false),
    ("• Author, Vault Cookbook    ", 5, false),
    ("  & App Store CAD tools.    ", 5, false),
    ("• RAPS invited team demo.   ", 5, false),
    ("", 5, false),
    ("EDUCATION:                  ", 12, true),
    ("• Master's Degree CompSci   ", 5, false),
    ("  (Computer Eng, 2003-08).  ", 5, false),
    ("  Dnipro National Univ.     ", 5, false),
    ("", 5, false),
    ("AVAILABILITY & CONTACT:     ", 6, true),
    ("• Target: Senior/Staff/     ", 5, false),
    ("  Lead/Architect (AI/CAD)   ", 5, false),
    ("• Vinnytsia, UA / Remote    ", 5, false),
    ("  worldwide (no relo).      ", 5, false),
    ("• dyemelianov@icloud.com    ", 7, true),
    ("• github: dmytro-yemelianov ", 7, true),
    ("• https://yemelianov.dev    ", 7, true),
];

pub static ABOUT_LINES_80: &[(&str, u8, bool)] = &[
    ("┌────────────┐   DMYTRO YEMELIANOV - LEAD SOFTWARE ARCHITECT", 6, true),
    ("│░▒▒▓▒▒░░░░░░│   Systems Engineering • AI Infrastructure • CAD/PLM", 5, false),
    ("│▒▓███░░░░░░░│   ───────────────────────────────────────────────────", 7, false),
    ("│▒▓▓▓▓▒▒░░░░░│   • 14+ years: C#/.NET, Rust, TypeScript, Python", 5, false),
    ("│▒▓▓▓▓░░▒░▒░░│   • Spec: High-throughput agentic platforms,", 5, false),
    ("│░░░░ ░░░▒▒░░│     multi-region AI/RAG systems, CAD/PLM motion IR", 5, false),
    ("│░░░ ░░░▓▒▓▓▒│   • Author of RAPS: Rust APS platform & 51 MCP tools", 5, false),
    ("└────────────┘   • Autodesk Expert Elite (Top ~100 globally)", 5, false),
    ("• Autodesk Developer Network (ADN) since 2012 • M.S. Computer Science", 5, false),
    ("• Location: Vinnytsia, Ukraine · Remote Worldwide (no relocation)", 5, false),
    ("• Direct contact: dyemelianov@icloud.com · https://yemelianov.dev", 7, true),
    ("", 5, false),
    ("SYSTEM ARCHITECTURE & TECHNICAL SPECIFICATION", 6, true),
    ("Dual-protocol pixel-first platform: Web (WASM/WebGL2) + SSH ANSI Daemon", 4, false),
    ("", 5, false),
    ("1. UNIFIED DUAL-INTERFACE ARCHITECTURE:", 7, true),
    ("┌────────────────────────────────────────────────────────┐", 3, false),
    ("│           RUST APPLICATION CORE & STATE                │", 7, true),
    ("│ (Input Events, Sessions, View Model, Zero State in UI) │", 4, false),
    ("└───────────────────────────┬────────────────────────────┘", 3, false),
    ("                            │ produces View model", 5, false),
    ("              ┌─────────────┴─────────────┐", 3, false),
    ("              ▼                           ▼", 6, true),
    ("   ┌────────────────────┐      ┌────────────────────┐", 3, false),
    ("   │ WEB PIXEL RENDERER │      │   ANSI RENDERER    │", 7, true),
    ("   │  Rust -> WASM32    │      │    Rust Native     │", 4, false),
    ("   │  8-bit Indexed FB  │      │ TrueColor/ANSI SSH │", 4, false),
    ("   │  WebGL2 Shader FX  │      │  PTY Session Host  │", 4, false),
    ("   └──────────┬─────────┘      └──────────┬─────────┘", 3, false),
    ("              ▼                           ▼", 6, true),
    ("   ┌────────────────────┐      ┌────────────────────┐", 3, false),
    ("   │ HTML5 CANVAS (GPU) │      │ TERMINAL (xterm)   │", 12, true),
    ("   │   https://...      │      │ ssh guest@...:2222 │", 12, true),
    ("   └────────────────────┘      └────────────────────┘", 3, false),
    ("", 5, false),
    ("2. PERFORMANCE & ARCHITECTURAL METRICS:", 7, true),
    ("┌────────────────────┬──────────────────────┬──────────────────────┐", 3, false),
    ("│ Metric / Component │ Target Specification │ Measured Value       │", 7, true),
    ("├────────────────────┼──────────────────────┼──────────────────────┤", 3, false),
    ("│ WASM Binary Size   │ < 200 KB compressed  │ 142 KB (54 KB brotli)│", 5, false),
    ("│ Framebuffer Memory │ 64 KB (indexed R8)   │ 64 KB (320x200x1)    │", 5, false),
    ("│ Cold Startup Time  │ < 500 ms             │ ~38 ms               │", 5, false),
    ("│ Frame Pipeline     │ Zero-copy R8 texture │ 60 FPS event-driven  │", 5, false),
    ("│ UI Frameworks      │ 0 KB (No React/DOM)  │ Pure Rust/WebGL2     │", 5, false),
    ("│ SSH PTY Transport  │ Native Rust Daemon   │ Russh (Async Tokio)  │", 5, false),
    ("│ Retro Emulation    │ Hardware ROM fonts   │ VGA, ZX, C64, Atari  │", 5, false),
    ("└────────────────────┴──────────────────────┴──────────────────────┘", 3, false),
    ("", 5, false),
    ("3. DEEP DIVE TECHNICAL IMPLEMENTATION:", 7, true),
    ("• 8-Bit Indexed Framebuffer: Memory holds byte indices into a 256-color palette.", 5, false),
    ("  The CPU never writes 32-bit RGBA pixels. WebGL2 fragment shader resolves", 5, false),
    ("  colors via a 256xRGBA uniform palette table in single-pass GPU execution.", 5, false),
    ("• Real-Time CRT Post-Processing: Hardware shaders simulate barrel glass curvature,", 5, false),
    ("  horizontal scanlines, phosphor persistence bloom, and chromatic aberration.", 5, false),
    ("• Authentic Hardware ROM Fonts: Embedded authentic glyph matrices for Sinclair ZX,", 5, false),
    ("  Commodore 64 PETSCII (901225-01), Atari 800 (REVAPAL), and IBM CP437.", 5, false),
    ("• Zero Idle CPU Overhead: Event-driven requestAnimationFrame loop only rerenders", 5, false),
    ("  when inputs arrive or marquee tickers fire. Idle CPU load is negligible.", 5, false),
    ("• Single Source of Truth View AST: Identical View data structure powers both the", 5, false),
    ("  interactive browser canvas and ANSI TrueColor terminal streams over SSH.", 5, false),
];

pub static ABOUT_LINES_40: &[(&str, u8, bool)] = &[
    ("┌────────┐  DMYTRO YEMELIANOV", 6, true),
    ("│░▒▒▒░░░░│  Software Architect", 5, false),
    ("│▒▓█▒░░░░│  AI Infra & CAD/PLM", 5, false),
    ("│▓██▒░░░░│  • 14y: C#/.NET, Rust", 5, false),
    ("│▒▓▓▒▒░░░│  • RAPS: 51 MCP tools", 5, false),
    ("│▒▓▓▒▒░░░│  • Autodesk Elite", 5, false),
    ("│░░░░░▒░░│  • ADN member '12", 5, false),
    ("│░░░░░▒▒▒│  • Vinnytsia, Ukraine", 5, false),
    ("│░░░ ▒▓▓▒│  • Remote Worldwide", 5, false),
    ("└────────┘  • yemelianov.dev", 7, true),
    ("• Contact: dyemelianov@icloud.com", 7, true),
    ("", 5, false),
    ("SYSTEM ARCHITECTURE & TECHNICAL SPECS:", 6, true),
    ("Dual-protocol: WebGL2 WASM + SSH ANSI", 4, false),
    ("", 5, false),
    ("1. DUAL-INTERFACE ARCHITECTURE:", 7, true),
    ("┌────────────────────────────────────┐", 3, false),
    ("│       RUST APPLICATION CORE        │", 7, true),
    ("│   (State, Sessions, View Model)    │", 4, false),
    ("└─────────────────┬──────────────────┘", 3, false),
    ("        ┌─────────┴─────────┐", 3, false),
    ("        ▼                   ▼", 6, true),
    ("┌────────────────┐ ┌─────────────────┐", 3, false),
    ("│  WEB RENDERER  │ │  ANSI RENDERER  │", 7, true),
    ("│  WASM / WebGL2 │ │  SSH / Terminal │", 4, false),
    ("└────────────────┘ └─────────────────┘", 3, false),
    ("", 5, false),
    ("2. PERFORMANCE BENCHMARKS:", 7, true),
    ("┌──────────────────┬─────────────────┐", 3, false),
    ("│ Metric           │ Measured Value  │", 7, true),
    ("├──────────────────┼─────────────────┤", 3, false),
    ("│ WASM Binary Size │ 142 KB (54K br) │", 5, false),
    ("│ Framebuffer Mem  │ 64 KB (indexed) │", 5, false),
    ("│ Cold Startup     │ ~38 ms          │", 5, false),
    ("│ UI Frameworks    │ 0 KB (Pure Rust)│", 5, false),
    ("│ SSH PTY Daemon   │ Russh Async     │", 5, false),
    ("│ Hardware Fonts   │ VGA,ZX,C64,Atari│", 5, false),
    ("└──────────────────┴─────────────────┘", 3, false),
    ("", 5, false),
    ("3. DEEP DIVE IMPLEMENTATION:", 7, true),
    ("• 8-Bit Indexed Framebuffer:", 6, true),
    ("  Memory holds byte indices into a", 5, false),
    ("  256-color palette. The CPU never", 5, false),
    ("  writes 32-bit RGBA pixels. WebGL2", 5, false),
    ("  fragment shader resolves colors", 5, false),
    ("  via 256xRGBA uniform palette table", 5, false),
    ("  in single-pass GPU execution.", 5, false),
    ("• Real-Time CRT Post-Processing:", 6, true),
    ("  Hardware shaders simulate barrel", 5, false),
    ("  glass curvature, scanlines, bloom", 5, false),
    ("  phosphor persistence & chromatic.", 5, false),
    ("• Authentic Hardware ROM Fonts:", 6, true),
    ("  Embedded authentic glyph matrices", 5, false),
    ("  for Sinclair ZX, Commodore 64", 5, false),
    ("  PETSCII, Atari 800 and IBM CP437.", 5, false),
    ("• Zero Idle CPU Overhead:", 6, true),
    ("  Event-driven animation loop only", 5, false),
    ("  rerenders when inputs arrive or", 5, false),
    ("  marquee tickers advance.", 5, false),
    ("• Single Source of Truth View AST:", 6, true),
    ("  Identical View data structure", 5, false),
    ("  powers both interactive browser", 5, false),
    ("  canvas and ANSI terminal streams.", 5, false),
];

pub static ABOUT_LINES_32: &[(&str, u8, bool)] = &[
    ("┌────────┐ DMYTRO YEMELIANOV", 6, true),
    ("│░▒▒▒░░░░│ Systems & AI Arch", 5, false),
    ("│▒▓█▒░░░░│ • 14y: .NET, Rust", 5, false),
    ("│▓██▒░░░░│ • RAPS (51 tools)", 5, false),
    ("│▒▓▓▒▒░░░│ • Autodesk Elite", 5, false),
    ("│▒▓▓▒▒░░░│ • ADN writer '13", 5, false),
    ("│░░░░░▒░░│ • Vinnytsia, UA", 5, false),
    ("│░░░░░▒▒▒│ • Remote Global", 5, false),
    ("│░░░ ▒▓▓▒│ • yemelianov.dev", 7, true),
    ("└────────┘ dyemelianov@icloud", 7, true),
    ("", 5, false),
    ("SYSTEM ARCHITECTURE:", 6, true),
    ("WebGL2 WASM + SSH ANSI", 4, false),
    ("", 5, false),
    ("1. DATAFLOW ARCHITECTURE:", 7, true),
    ("┌───────────────────────────┐", 3, false),
    ("│   RUST APPLICATION CORE   │", 7, true),
    ("│  (State & View Model AST) │", 4, false),
    ("└─────────────┬─────────────┘", 3, false),
    ("       ┌──────┴──────┐", 3, false),
    ("       ▼             ▼", 6, true),
    ("┌────────────┐┌─────────────┐", 3, false),
    ("│ WEB (WASM) ││ SSH (ANSI)  │", 7, true),
    ("│ WebGL2 R8  ││ TrueColor   │", 4, false),
    ("└────────────┘└─────────────┘", 3, false),
    ("", 5, false),
    ("2. BENCHMARKS & METRICS:", 7, true),
    ("┌─────────────┬─────────────┐", 3, false),
    ("│ METRIC      │ MEASURED    │", 7, true),
    ("├─────────────┼─────────────┤", 3, false),
    ("│ WASM Binary │ 142K (54Kbr)│", 5, false),
    ("│ Framebuffer │ 64 KB R8    │", 5, false),
    ("│ Cold Start  │ ~38 ms      │", 5, false),
    ("│ UI Deps     │ 0 KB (Rust) │", 5, false),
    ("│ SSH Server  │ Russh Async │", 5, false),
    ("└─────────────┴─────────────┘", 3, false),
    ("", 5, false),
    ("3. TECHNICAL DEEP DIVE:", 7, true),
    ("• 8-Bit Indexed Framebuffer:", 6, true),
    ("  Memory holds byte indices ", 5, false),
    ("  into a 256-color palette. ", 5, false),
    ("  CPU never writes RGBA.    ", 5, false),
    ("  WebGL2 fragment shader    ", 5, false),
    ("  resolves colors via GPU   ", 5, false),
    ("  uniform palette table.    ", 5, false),
    ("• Real-Time CRT Shaders:    ", 6, true),
    ("  Barrel curvature, scanline", 5, false),
    ("  glow, phosphor persistence", 5, false),
    ("  and chromatic aberration. ", 5, false),
    ("• Authentic Hardware Fonts: ", 6, true),
    ("  Embedded ROM glyphs for   ", 5, false),
    ("  Sinclair ZX, C64 PETSCII, ", 5, false),
    ("  Atari 800 and IBM CP437.  ", 5, false),
    ("• Zero Idle CPU Overhead:   ", 6, true),
    ("  Event-driven render loop  ", 5, false),
    ("  rerenders only on inputs  ", 5, false),
    ("  or marquee ticker steps.  ", 5, false),
    ("• Unified View AST:         ", 6, true),
    ("  Identical View AST powers ", 5, false),
    ("  browser canvas and SSH    ", 5, false),
    ("  ANSI TrueColor streams.   ", 5, false),
];

pub mod details;
pub mod profile;
pub use details::{get_project_detail, project_detail_lines, ProjectDetail};
pub use profile::{get_profile_sprite, PROFILE_SPRITE_64_VGA, PROFILE_SPRITE_96_VGA};


